### ISSUE TITLE
windows_smb_share is in trouble with User Profil Disk

### ISSUE THREAD

**Issue by DamienRaimon** [karmafeast/windows_smb#5]
Hi,
I've got some troubles with your module. I set the sharing of the profil$ folder with Puppet. The problem is that when we change the list of users, there is like a cleanup, this create a bug on connected users on the terminal server.

**Comment by karmafeast** [comment]
Hi @DamienRaimon 

There were some eccentricities in the PowerShell used for this when I did it, and I remember this being an issue.

I recommend using groups for permissions on the shares, then modifying membership of those groups in Active Directory - this prevents a share acl change on a per-user basis, and tear down and recreate of the share.

If I get some time I'll have a revisit of this module and see if I can get that to not be a limitation.

**Comment by DamienRaimon** [comment]
Oh thank you very much for this information, I will try this.

**Comment by DamienRaimon** [comment]
I come to realise that the use of groups won't be good for me cause it is something manual. Could you maybe tell me on : damien.raimon@gmail.com when you've got time to solve this ?
